source 'https://rubygems.org'

group :test do 
	gem 'cucumber'
	gem 'gherkin'
	gem 'json', '~> 1.7.7'
  gem 'rspec-expectations'
  gem 'capybara'
  gem 'selenium-webdriver'
  #gem 'capybara-webkit'
  gem 'poltergeist'
end


